### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by echan00** [jrouillard/TileGen#1]
Hello, 

I tried your library and it generated the following images. It doesn't look right, is this correct?

![debug](https://user-images.githubusercontent.com/6287299/102682469-9a93e300-417e-11eb-896a-ae0fd5893395.png)
![result](https://user-images.githubusercontent.com/6287299/102682471-9b2c7980-417e-11eb-93ca-abfd5e344efd.png)

**Comment by jrouillard** [comment]
Hello!
Yes, sorry for the wait, that is the intended result indeed. The first image is a debug one and I should remove it, the second one is the atlas generated.

Maybe the purpose of the lib is not clear, it is a tool to generate an atlas with all the possible connections between them, and to use it in combination with "bitmasking":
https://gamedevelopment.tutsplus.com/tutorials/how-to-use-tile-bitmasking-to-auto-tile-your-level-layouts--cms-25673
The algo is cool, but you still need to draw all the tiles by hand.

This tool allows to generate all the 48 possible connections from the 2 entry tiles. It's not perfect but it's much faster to fix the results than drawing it all from scratch. You can also add a background (the earth below it) for the isometric tiles that require height (like my game needs)
I'll edit the readme so it is clearer, do not hesitate if you still have questions.

Also, you can run gui.py to have an user interface like this, if it's clearer:
![image](https://user-images.githubusercontent.com/1590758/102696102-26b01400-422c-11eb-94ee-2e0ed7c2cf46.png)

**Comment by jrouillard** [comment]
I've updated the readme with gifs and more descriptions (and fixed the whole project so you better pull the whole thing)

I know a couple of tools that could help you more than this one, depending of your use case.

[Tilesetter](https://led.itch.io/tilesetter) is probably the most features complete tool, but it's not free and it does not support isometric yet

[isometric-tileset-generator](https://melikepixels.itch.io/isometric-tileset-generator) is actually my inspiration; it does the same thing but much simpler (no height/frames) and it does not work if your image is not divisible by 3

**Comment by echan00** [comment]
This is great @jrouillard thanks for your information and updating the readme. Will ping you if I have any questions, I need something that works programmatically and this is perfect
